/**
 * DNS
 * Manage dns zones and records
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@liara.ir
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class DnsRecordId {
    /**
    * The id of dns record which need in PUT, DELETE and GET method
    */
    'id'?: string;
    /**
    * The name of dns record, \"@\" for zone name(root level), \"*\" for wild card and any valid value with RFC 1123
    */
    'name'?: string;
    /**
    * The type of dns record, valid values: [A, AAAA, TXT, CNAME, ALIAS, MX, SRV, CAA]
    */
    'type'?: string;
    /**
    * The ttl of dns record, is not required, valid values: [120, 180, 300, 600, 900, 1800, 3600, 7200, 18000, 43200, 86400, 172800, 432000]
    */
    'ttl'?: number;
    /**
    * Array of content of dns record, change base on type of dns record
    */
    'contents'?: Array<any>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "ttl",
            "baseName": "ttl",
            "type": "number",
            "format": ""
        },
        {
            "name": "contents",
            "baseName": "contents",
            "type": "Array<any>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DnsRecordId.attributeTypeMap;
    }

    public constructor() {
    }
}

