/**
 * DNS
 * Manage dns zones and records
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@liara.ir
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class Zone {
    /**
    * The name of the zone, “liara.ir”, max length: 253, pattern: ^([a-zA-Z0-9][\\-a-zA-Z0-9]*\\.)+[\\-a-zA-Z0-9]{2,20}$
    */
    'name'?: string;
    /**
    * The status of the zone, valid values: [CREATING, PENDING, ACTIVE, DELETING]
    */
    'status'?: string;
    'nameServers'?: Array<string>;
    'currentNameServers'?: Array<string>;
    /**
    * Last time when zones nameservers was checked
    */
    'lastCheckAt'?: string;
    /**
    * Time when zone was created
    */
    'createdAt'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "nameServers",
            "baseName": "nameServers",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "currentNameServers",
            "baseName": "currentNameServers",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "lastCheckAt",
            "baseName": "lastCheckAt",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Zone.attributeTypeMap;
    }

    public constructor() {
    }
}

