/**
 * Liara Mail API Documentaion
 * A fully featured mail delivery platform for incoming & outgoing e-mail
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@liara.ir
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CheckDNSResponseDnsSetupDkim {
    'dkimError'?: string;
    'dkimRecord'?: string;
    'dkimRecordName'?: string;
    'dkimStatus'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "dkimError",
            "baseName": "dkim_error",
            "type": "string",
            "format": ""
        },
        {
            "name": "dkimRecord",
            "baseName": "dkim_record",
            "type": "string",
            "format": ""
        },
        {
            "name": "dkimRecordName",
            "baseName": "dkim_record_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "dkimStatus",
            "baseName": "dkim_status",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CheckDNSResponseDnsSetupDkim.attributeTypeMap;
    }

    public constructor() {
    }
}

