/**
 * Liara Mail API Documentaion
 * A fully featured mail delivery platform for incoming & outgoing e-mail
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@liara.ir
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CheckDNSResponseDnsSetupDkim } from '../models/CheckDNSResponseDnsSetupDkim';
import { CheckDNSResponseDnsSetupMxRecord } from '../models/CheckDNSResponseDnsSetupMxRecord';
import { CheckDNSResponseDnsSetupReturnPath } from '../models/CheckDNSResponseDnsSetupReturnPath';
import { CheckDNSResponseDnsSetupSpf } from '../models/CheckDNSResponseDnsSetupSpf';
import { HttpFile } from '../http/http';

export class CheckDNSResponseDnsSetup {
    'dkim'?: CheckDNSResponseDnsSetupDkim;
    'mxRecord'?: CheckDNSResponseDnsSetupMxRecord;
    'returnPath'?: CheckDNSResponseDnsSetupReturnPath;
    'spf'?: CheckDNSResponseDnsSetupSpf;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "dkim",
            "baseName": "dkim",
            "type": "CheckDNSResponseDnsSetupDkim",
            "format": ""
        },
        {
            "name": "mxRecord",
            "baseName": "mx_record",
            "type": "CheckDNSResponseDnsSetupMxRecord",
            "format": ""
        },
        {
            "name": "returnPath",
            "baseName": "return_path",
            "type": "CheckDNSResponseDnsSetupReturnPath",
            "format": ""
        },
        {
            "name": "spf",
            "baseName": "spf",
            "type": "CheckDNSResponseDnsSetupSpf",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CheckDNSResponseDnsSetup.attributeTypeMap;
    }

    public constructor() {
    }
}

