/**
 * Liara Mail API Documentaion
 * A fully featured mail delivery platform for incoming & outgoing e-mail
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@liara.ir
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CheckDNSResponseDnsSetup } from '../models/CheckDNSResponseDnsSetup';
import { HttpFile } from '../http/http';

export class CheckDNSResponse {
    'dnsSetup'?: CheckDNSResponseDnsSetup;
    'user'?: string;
    'domain'?: string;
    'recordsStatus'?: string;
    'mode'?: string;
    'status'?: string;
    'checkDNSRecord'?: boolean;
    'createdAt'?: string;
    'updatedAt'?: string;
    'id'?: string;
    'smtpServer'?: string;
    'smtpPort'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "dnsSetup",
            "baseName": "dns_setup",
            "type": "CheckDNSResponseDnsSetup",
            "format": ""
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "string",
            "format": ""
        },
        {
            "name": "domain",
            "baseName": "domain",
            "type": "string",
            "format": ""
        },
        {
            "name": "recordsStatus",
            "baseName": "recordsStatus",
            "type": "string",
            "format": ""
        },
        {
            "name": "mode",
            "baseName": "mode",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "checkDNSRecord",
            "baseName": "checkDNSRecord",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "smtpServer",
            "baseName": "smtp_server",
            "type": "string",
            "format": ""
        },
        {
            "name": "smtpPort",
            "baseName": "smtp_port",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CheckDNSResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

