/**
 * Liara Mail API Documentaion
 * A fully featured mail delivery platform for incoming & outgoing e-mail
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@liara.ir
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CountMailPerDayDataEmailPerDayInner {
    'count'?: number;
    'date'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "count",
            "baseName": "count",
            "type": "number",
            "format": ""
        },
        {
            "name": "date",
            "baseName": "date",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CountMailPerDayDataEmailPerDayInner.attributeTypeMap;
    }

    public constructor() {
    }
}

