/**
 * Liara Mail API Documentaion
 * A fully featured mail delivery platform for incoming & outgoing e-mail
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@liara.ir
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class MailInboundRulesDataMailInboundrulesInner {
    'createdAt'?: string;
    'rule'?: string;
    'mailServer'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "string",
            "format": ""
        },
        {
            "name": "rule",
            "baseName": "rule",
            "type": "string",
            "format": ""
        },
        {
            "name": "mailServer",
            "baseName": "mailServer",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MailInboundRulesDataMailInboundrulesInner.attributeTypeMap;
    }

    public constructor() {
    }
}

