/**
 * Liara Mail API Documentaion
 * A fully featured mail delivery platform for incoming & outgoing e-mail
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@liara.ir
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MailInboundRulesDataMailInboundrulesInner } from '../models/MailInboundRulesDataMailInboundrulesInner';
import { HttpFile } from '../http/http';

export class MailInboundRulesData {
    'mailInboundrules'?: Array<MailInboundRulesDataMailInboundrulesInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "mailInboundrules",
            "baseName": "mailInboundrules",
            "type": "Array<MailInboundRulesDataMailInboundrulesInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MailInboundRulesData.attributeTypeMap;
    }

    public constructor() {
    }
}

