/**
 * Liara Mail API Documentaion
 * A fully featured mail delivery platform for incoming & outgoing e-mail
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@liara.ir
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MailForwardsDataForwardersInner } from '../models/MailForwardsDataForwardersInner';
import { HttpFile } from '../http/http';

export class MailForwardsData {
    'forwarders'?: Array<MailForwardsDataForwardersInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "forwarders",
            "baseName": "forwarders",
            "type": "Array<MailForwardsDataForwardersInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MailForwardsData.attributeTypeMap;
    }

    public constructor() {
    }
}

