/**
 * Liara Mail API Documentaion
 * A fully featured mail delivery platform for incoming & outgoing e-mail
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@liara.ir
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class MailServer {
    'id'?: string;
    'mode'?: string;
    'recordsStatus'?: string;
    'smtpPort'?: string;
    'smtpServer'?: string;
    'plan'?: any;
    'domain'?: string;
    'createdAt'?: string;
    'dnsSetup'?: string;
    'rateLimitTier'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "mode",
            "baseName": "mode",
            "type": "string",
            "format": ""
        },
        {
            "name": "recordsStatus",
            "baseName": "recordsStatus",
            "type": "string",
            "format": ""
        },
        {
            "name": "smtpPort",
            "baseName": "smtp_port",
            "type": "string",
            "format": ""
        },
        {
            "name": "smtpServer",
            "baseName": "smtp_server",
            "type": "string",
            "format": ""
        },
        {
            "name": "plan",
            "baseName": "plan",
            "type": "any",
            "format": ""
        },
        {
            "name": "domain",
            "baseName": "domain",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "string",
            "format": ""
        },
        {
            "name": "dnsSetup",
            "baseName": "dns_setup",
            "type": "string",
            "format": ""
        },
        {
            "name": "rateLimitTier",
            "baseName": "rateLimitTier",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MailServer.attributeTypeMap;
    }

    public constructor() {
    }
}

