/**
 * Liara Mail API Documentaion
 * A fully featured mail delivery platform for incoming & outgoing e-mail
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@liara.ir
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Timeout } from '../models/Timeout';
import { HttpFile } from '../http/http';

export class Model7 {
    'description'?: string;
    'name': string;
    'attachment'?: boolean;
    'address': string;
    'timeout'?: Timeout;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "attachment",
            "baseName": "attachment",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "string",
            "format": ""
        },
        {
            "name": "timeout",
            "baseName": "timeout",
            "type": "Timeout",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Model7.attributeTypeMap;
    }

    public constructor() {
    }
}



