/**
 * Liara Mail API Documentaion
 * A fully featured mail delivery platform for incoming & outgoing e-mail
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@liara.ir
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SMTPDataCredentialsInner } from '../models/SMTPDataCredentialsInner';
import { HttpFile } from '../http/http';

export class SMTPData {
    'credentials'?: Array<SMTPDataCredentialsInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "credentials",
            "baseName": "credentials",
            "type": "Array<SMTPDataCredentialsInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SMTPData.attributeTypeMap;
    }

    public constructor() {
    }
}

