/**
 * PaaS
 * Manage your apps using our API  [wss://api.iran.liara.ir?token=<api-token>&cmd=/bin/bash&project_id=<project-id>]( wss://api.iran.liara.ir?token=<api-token>&cmd=/bin/bash&project_id=<project-id>)  Parameters: - `token`: Your api token in liara - `cmd`: By default /bin/bash - `project_id`: The id of your project in liara  This `WebSocket` endpoint allows `real-time` communication with the projects service hosted at `Liara` You can use `WebSocket protocols` to send and receive data, enabling efficient and low-latency interactions with the projects
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@liara.ir
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppletsAppletsInnerRelease } from '../models/AppletsAppletsInnerRelease';
import { HttpFile } from '../http/http';

export class AppletsAppletsInner {
    /**
    * The id of applet
    */
    'id'?: string;
    /**
    * The name of applet
    */
    'name'?: string;
    /**
    * The timestamp of applet
    */
    'timestamp'?: string;
    /**
    * The state of applet
    */
    'state'?: string;
    /**
    * The reason of applet
    */
    'reason'?: string;
    'release'?: AppletsAppletsInnerRelease;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "string",
            "format": ""
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "string",
            "format": ""
        },
        {
            "name": "reason",
            "baseName": "reason",
            "type": "string",
            "format": ""
        },
        {
            "name": "release",
            "baseName": "release",
            "type": "AppletsAppletsInnerRelease",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AppletsAppletsInner.attributeTypeMap;
    }

    public constructor() {
    }
}

