/**
 * PaaS
 * Manage your apps using our API  [wss://api.iran.liara.ir?token=<api-token>&cmd=/bin/bash&project_id=<project-id>]( wss://api.iran.liara.ir?token=<api-token>&cmd=/bin/bash&project_id=<project-id>)  Parameters: - `token`: Your api token in liara - `cmd`: By default /bin/bash - `project_id`: The id of your project in liara  This `WebSocket` endpoint allows `real-time` communication with the projects service hosted at `Liara` You can use `WebSocket protocols` to send and receive data, enabling efficient and low-latency interactions with the projects
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@liara.ir
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CheckDomainDomainProject } from '../models/CheckDomainDomainProject';
import { HttpFile } from '../http/http';

export class CheckDomainDomain {
    'id'?: string;
    'user'?: string;
    'name'?: string;
    'type'?: string;
    'project'?: CheckDomainDomainProject;
    'status'?: string;
    'certificatesStatus'?: string;
    'redirectTo'?: string;
    'redirectStatus'?: number;
    'updatedAt'?: string;
    'punycodeName'?: string;
    'verificationCode'?: string;
    'createdAt'?: string;
    'v'?: number;
    'cNameRecord'?: string;
    'issuedAt'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "project",
            "baseName": "project",
            "type": "CheckDomainDomainProject",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "certificatesStatus",
            "baseName": "certificatesStatus",
            "type": "string",
            "format": ""
        },
        {
            "name": "redirectTo",
            "baseName": "redirectTo",
            "type": "string",
            "format": ""
        },
        {
            "name": "redirectStatus",
            "baseName": "redirectStatus",
            "type": "number",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "punycodeName",
            "baseName": "punycodeName",
            "type": "string",
            "format": ""
        },
        {
            "name": "verificationCode",
            "baseName": "verificationCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "v",
            "baseName": "__v",
            "type": "number",
            "format": ""
        },
        {
            "name": "cNameRecord",
            "baseName": "CNameRecord",
            "type": "string",
            "format": ""
        },
        {
            "name": "issuedAt",
            "baseName": "issuedAt",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CheckDomainDomain.attributeTypeMap;
    }

    public constructor() {
    }
}

