/**
 * PaaS
 * Manage your apps using our API  [wss://api.iran.liara.ir?token=<api-token>&cmd=/bin/bash&project_id=<project-id>]( wss://api.iran.liara.ir?token=<api-token>&cmd=/bin/bash&project_id=<project-id>)  Parameters: - `token`: Your api token in liara - `cmd`: By default /bin/bash - `project_id`: The id of your project in liara  This `WebSocket` endpoint allows `real-time` communication with the projects service hosted at `Liara` You can use `WebSocket protocols` to send and receive data, enabling efficient and low-latency interactions with the projects
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@liara.ir
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DomainsDomainsInnerProject } from '../models/DomainsDomainsInnerProject';
import { HttpFile } from '../http/http';

export class DomainsDomainsInner {
    /**
    * The id of domain
    */
    'id'?: string;
    /**
    * The name of domain
    */
    'name'?: string;
    /**
    * The type of domain
    */
    'type'?: string;
    'project'?: DomainsDomainsInnerProject;
    /**
    * The status of domain
    */
    'status'?: string;
    /**
    * The certificatesStatus of domain
    */
    'certificatesStatus'?: string;
    /**
    * The redirectTo of domain
    */
    'redirectTo'?: string;
    /**
    * The redirectStatus of domain
    */
    'redirectStatus'?: number;
    /**
    * The created_at of domain
    */
    'createdAt'?: string;
    /**
    * The CNameRecord of domain
    */
    'cNameRecord'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "project",
            "baseName": "project",
            "type": "DomainsDomainsInnerProject",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "certificatesStatus",
            "baseName": "certificatesStatus",
            "type": "string",
            "format": ""
        },
        {
            "name": "redirectTo",
            "baseName": "redirectTo",
            "type": "string",
            "format": ""
        },
        {
            "name": "redirectStatus",
            "baseName": "redirectStatus",
            "type": "number",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "cNameRecord",
            "baseName": "CNameRecord",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DomainsDomainsInner.attributeTypeMap;
    }

    public constructor() {
    }
}

