/**
 * PaaS
 * Manage your apps using our API  [wss://api.iran.liara.ir?token=<api-token>&cmd=/bin/bash&project_id=<project-id>]( wss://api.iran.liara.ir?token=<api-token>&cmd=/bin/bash&project_id=<project-id>)  Parameters: - `token`: Your api token in liara - `cmd`: By default /bin/bash - `project_id`: The id of your project in liara  This `WebSocket` endpoint allows `real-time` communication with the projects service hosted at `Liara` You can use `WebSocket protocols` to send and receive data, enabling efficient and low-latency interactions with the projects
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@liara.ir
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ReleasesReleasesInner } from '../models/ReleasesReleasesInner';
import { HttpFile } from '../http/http';

export class Releases {
    /**
    * The total of releases
    */
    'total'?: number;
    /**
    * The currentRelease of releases
    */
    'currentRelease'?: string;
    /**
    * The total of releases
    */
    'readyReleasesCount'?: number;
    /**
    * The total of releases
    */
    'releases'?: Array<ReleasesReleasesInner>;
    'platform'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "total",
            "baseName": "total",
            "type": "number",
            "format": ""
        },
        {
            "name": "currentRelease",
            "baseName": "currentRelease",
            "type": "string",
            "format": ""
        },
        {
            "name": "readyReleasesCount",
            "baseName": "readyReleasesCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "releases",
            "baseName": "releases",
            "type": "Array<ReleasesReleasesInner>",
            "format": ""
        },
        {
            "name": "platform",
            "baseName": "platform",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Releases.attributeTypeMap;
    }

    public constructor() {
    }
}

