/**
 * DBaaS
 * Manage your databases using our API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@liara.ir
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ReportsResultInner } from '../models/ReportsResultInner';
import { HttpFile } from '../http/http';

export class Reports {
    'end'?: number;
    'result'?: Array<ReportsResultInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "end",
            "baseName": "end",
            "type": "number",
            "format": ""
        },
        {
            "name": "result",
            "baseName": "result",
            "type": "Array<ReportsResultInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Reports.attributeTypeMap;
    }

    public constructor() {
    }
}

